version: 2

root-markers:
  - .git/
lint-debounce: 1s

tools:
  md-rumdl: &md-rumdl
    format-command: 'rumdl fmt --stdin --stdin-filename ${INPUT} --quiet'
    format-stdin: true
    lint-command: 'rumdl check --stdin --stdin-filename ${INPUT}'
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c: %m'

  yaml-yamlfmt: &yaml-yamlfmt
    format-command: 'yamlfmt -in'
    format-stdin: true

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

languages:
  markdown:
    - <<: *md-rumdl

  yaml:
    - <<: *yaml-yamlfmt
    - <<: *yaml-yamllint
