#!/usr/bin/env bash

# shellcheck enable=all

# check if not interactive or in POSIX mode
[[ $- != *i* ]] && [[ $- == *p* ]] && return

# early ble
if [[ -f "${HOME}/.local/share/blesh/ble.sh" ]]; then
    # shellcheck disable=SC1091 # can't follow source
    source -- "${HOME}/.local/share/blesh/ble.sh" --attach=none
fi

### environment

# path: home, $PATH, sbin
# global is assumed to contain at least: /usr/local/bin:/usr/bin:/bin
PATH=${HOME}/bin:${HOME}/.local/bin:${PATH}:/usr/local/sbin:/usr/sbin:/sbin

# noramlize locale
LANG=en_US.UTF-8

# test strings
export SPHINX="sphinx of black quartz judge my vow\nSPHINX OF BLACK QUARTZ JUDGE MY VOW"
export UNDERCURL="\e[4:3m\e[58:2:63:127:255mundercurl"

# set window size
shopt -s checkwinsize

# recursive glob
shopt -s globstar 2>/dev/null

# case-insensitive glob
shopt -s nocaseglob

# append, not overwrite, history
shopt -s histappend

# save multi-line commands as single entry with embedded newlines
shopt -s cmdhist
shopt -s lithist

# force expand variable in tab complete to prevent escaping $
shopt -s direxpand

# unlimited power
HISTSIZE=9001
HISTFILESIZE=9001

# ignore deps
HISTCONTROL="erasedups:ignoreboth"

# don't record useless commands
HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"

# set MANPATH early
MANPATH="${HOME}/.local/share/man:$(manpath -g)"
export MANPATH

# remove green background for o+w dirs; can't read blue on green
# wsl2's 9p2000 bridge doesn't filter these perms
eval "$(dircolors || true)"
shopt -s extglob
LS_COLORS="${LS_COLORS/:ow=*([^:]):/:ow=:}"
shopt -u extglob
export LS_COLORS

# check for 24 bit support
if [[ "${TERM}" = "xterm"* ||
    "${TERM}" = "tmux"* ||
    "${TERM}" = "alacritty"* ||
    "${TERM}" = "wezterm"* ]]; then
    export COLORTERM="truecolor"
fi

# load local Win config
if [[ -x "${HOME}/.bashrc.win" ]]; then
    # shellcheck disable=SC1091 # can't follow source
    source "${HOME}/.bashrc.win"
fi

# load local config
if [[ -x "${HOME}/.bashrc.local" ]]; then
    # shellcheck disable=SC1091 # can't follow source
    source "${HOME}/.bashrc.local"
fi

### readline

# ignore case for autocomplete
bind "set completion-ignore-case on"

# ... including - and _
bind "set completion-map-case on"

# don't require tab twice to get list
bind "set show-all-if-ambiguous on"

# insert / after directory names when tab completed
bind "set mark-directories on"

# also do this for symlinks
bind "set mark-symlinked-directories on"

# colors
bind "set colored-completion-prefix on"
bind "set colored-stats on"

### prompt

# git-prompt
GIT_PS1_SHOWCOLORHINTS=true
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWSTASHSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWUPSTREAM=auto

if [[ -e /usr/lib/git-core/git-sh-prompt ]]; then
    # shellcheck disable=SC1091 # can't follow source
    source /usr/lib/git-core/git-sh-prompt
fi

# styles
RESET="$(tput sgr0)"
REV="$(tput rev)"
RED="$(tput setaf 1)"

HOSTCHECKSUM="$(echo "${HOSTNAME}" | md5sum | tr '[:lower:]' '[:upper:]' | cut -b1-2)"
HOSTCOLOR="$((16#"${HOSTCHECKSUM}" % 16))"

if [[ "${HOSTCOLOR}" -eq 0 ]]; then
    PRO_FG="${REV}$(tput setaf "${HOSTCOLOR}")"
else
    PRO_FG="$(tput setaf "${HOSTCOLOR}")"
fi

unset HOSTCHECKSUM
unset HOSTCOLOR

# set prompt
PRO_START="\[${RESET}\][\[${PRO_FG}\]\\h\[${RESET}\] \\W"

id="$(id -u)"
if [[ "${id}" -eq 0 ]]; then
    PRO_END="]\[${RED}\]\#\[${RESET}\] "
else
    PRO_END="]\$\[${RESET}\] "
fi
unset id

precmd() {
    local git_check
    git_check="$(type -t __git_ps1)"

    if [[ "${PWD}" != "${HOME}" ]] && [[ "${git_check}" = "function" ]]; then
        __git_ps1 "${PRO_START}" "${PRO_END}"
    else
        PS1="${PRO_START}${PRO_END}"
    fi
}

PROMPT_COMMAND=precmd

# set xterm title
preexec() {
    if [[ "${BASH_COMMAND}" == "precmd" ]]; then
        COMMAND="${PWD/${HOME}/\~}"
    else
        COMMAND="${BASH_COMMAND//[^[:print:]]/}"
    fi

    printf "\e]2;%s: %s\a" "${HOSTNAME%%.*}" "${COMMAND}"

    history -a
}

trap preexec DEBUG

### completion and fuzzy finding

# ble.sh
if [[ -n ${BLE_VERSION:-} ]]; then
    bleopt term_index_colors=
    bleopt filename_ls_colors="${LS_COLORS}"
    bleopt highlight_syntax=
    bleopt highlight_filename=
    bleopt highlight_variable=
    bleopt color_scheme=base16
    # shellcheck disable=SC1090 # non-constant source
    source <((ble-face | sed 's/,*underline//') || true)
    ble-face auto_complete=fg=gray

    bleopt prompt_eol_mark=''
    bleopt exec_errexit_mark=
    bleopt exec_elapsed_mark=
    bleopt exec_exit_mark=
    bleopt edit_marker=
    bleopt edit_marker_error=

    ble-bind -m auto_complete -f S-C-i auto_complete/insert
    ble-bind -m auto_complete -f S-TAB auto_complete/insert
fi

# completion
if command -v carapace >/dev/null 2>&1; then
    export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense'
    # shellcheck disable=SC1090 # non-constant source
    source <(carapace _carapace || true)
elif [[ -f /usr/share/bash-completion/bash_completion ]]; then
    source /usr/share/bash-completion/bash_completion
fi

# fzf
# https://github.com/junegunn/fzf#settings
# https://github.com/tavianator/bfs/discussions/119#discussioncomment-6533106
FZF_COMPLETION_TRIGGER=""

set -- +m -0 -1 --bind 'tab:down,btab:up' --info='hidden' --no-bold --color='fg:7,bg:-1,hl:2,fg+:15,bg+:8,hl+:10,pointer:4,pointer:12,gutter:-1' --layout='reverse-list' --ansi --no-separator
FZF_DEFAULT_OPTS="$*"
FZF_CTRL_R_OPTS="--no-sort --exact"

if command -v fzf >/dev/null 2>&1; then
    if command -v bfs >/dev/null 2>&1; then
        _fzf_compgen_path() {
            bfs -H "$1" -color -exclude \( -name .git \) 2>/dev/null
        }

        _fzf_compgen_dir() {
            bfs -H "$1" -color -exclude \( -name .git \) -type d 2>/dev/null
        }

        set -- bfs -color -mindepth 1 -exclude \( -name .git \) -printf '%P\n' 2>/dev/null
        FZF_CTRL_T_COMMAND="$*"

        set -- bfs -color -mindepth 1 -exclude \( -name .git \) -type d -printf '%P\n' 2>/dev/null
        FZF_ALT_C_COMMAND="$*"
    elif command -v fd >/dev/null 2>&1; then
        _fzf_compgen_path() {
            fd --hidden --follow --exclude '.git' . "$1"
        }

        _fzf_compgen_dir() {
            fd --type d --hidden --follow --exclude '.git' . "$1"
        }

        set -- fd --hidden --follow --exclude '.git' .
        FZF_CTRL_T_COMMAND="$*"

        set -- fd -t d --hidden --follow --exclude '.git' .
        FZF_ALT_C_COMMAND="$*"
    fi

    if [[ -n ${BLE_VERSION-} ]]; then
        ble-import -d integration/fzf-completion
        ble-import -d integration/fzf-key-bindings
        ble-import -d integration/fzf-menu
        true
    else
        eval "$(fzf --bash || true)"
    fi

    export FZF_COMPLETION_TRIGGER FZF_DEFAULT_OPTS FZF_CTRL_R_OPTS FZF_CTRL_T_COMMAND FZF_CTRL_T_OPTS FZF_ALT_C_COMMAND FZF_ALT_C_OPTS
fi

### programs

# alias
alias bc="bc -ql"
alias grep="grep --color=auto"
alias ls="ls --color=auto"

# rust/cargo
PATH="${HOME}/.cargo/bin:${PATH}"

# nodejs/npm
export NPMPATH="${HOME}/.npm/lib/node_modules"

# shellcheck disable=SC1091 # can't follow source
PATH="${HOME}/.npm/bin:${PATH}"
export MANPATH="${NPMPATH}/share/man:${MANPATH}"

#fd
if command -v fdfind >/dev/null 2>&1; then
    alias fd="fdfind"
fi

# sccache
if [[ -x "${HOME}/.cargo/bin/sccache" ]]; then
    export RUSTC_WRAPPER="${HOME}/.cargo/bin/sccache"
    export CARGO_INCREMENTAL="false"

    export CC="${HOME}/.cargo/bin/sccache gcc"
    export CXX="${HOME}/.cargo/bin/sccache g++"

    export CMAKE_C_COMPILER_LAUNCHER="${HOME}/.cargo/bin/sccache"
    export CMAKE_CXX_COMPILER_LAUNCHER="${HOME}/.cargo/bin/sccache"
fi

# vim and helix
if command -v nvim >/dev/null 2>&1; then
    export EDITOR=nvim
    alias vim=nvim
else
    export EDITOR=vim
fi

export GIT_EDITOR="${EDITOR}"

# late ble.sh
[[ -n ${BLE_VERSION:-} ]] && ble-attach
