#!/bin/sh

# shellcheck enable=all

# Exit immediately if a command exits with a non-zero status
set -e

# Treat unset variables as an error when substituting
set -u

user="twpayne"
proj="chezmoi"
asset="chezmoi-linux-amd64-musl"
target_dir="${HOME}/.local/bin"
target_bin="chezmoi"

rm -f "/tmp/latest.json"
wget -q "https://api.github.com/repos/${user}/${proj}/releases/latest" -O "/tmp/latest.json"

# Match '"tag_name":', one or more whitespace, a double quote, "v",
# then flush the match; match one or more non-whitespace until you
# reach one a double quote.
regex='"tag_name":\s*"v\K\S+(?=")'
ver="$(grep -oP "${regex}" "/tmp/latest.json")"
url="https://github.com/${user}/${proj}/releases/download/v${ver}/${asset}"

tmp="/tmp/${asset}"

printf "Downloading %s %s\n" "${asset}" "${ver}"

rm -f "${tmp}"
if wget -q "${url}" -O "${tmp}" > /dev/null; then
  mkdir -p "${target_dir}"
  mv "${tmp}" "${target_dir}/${target_bin}"
  chmod +x "${target_dir}/${target_bin}"
else
  printf "Failed to download %s\n" "${url}"
fi
