#!/usr/bin/env bash

GREEN="$(tput setaf 2)"
RESET="$(tput sgr0)"
OFFSET=0

function _start()
{
    if [ $OFFSET -ne 0 ]; then
    OFFSET=0
    echo -e ""
    fi

    echo -e "$GREEN==> $1$RESET"
}

function _end()
{
    OFFSET=0
    echo -e ""
}

function _status()
{
    OFFSET=1
    echo -e "$1"
}

function _mkdir {
    mkdir -vp "$1"
}

function _ln {
    _mkdir $(dirname "$2")
    rm -f "$2"
    ln -sTv "$1" "$2"
}

function _ln_descent {
    SRC_DIR="$1"
    DST_DIR="$2"

    for SRC in "$SRC_DIR"/**; do
      if [ -f $SRC ]; then
        DST="${SRC#$SRC_DIR/}"
        _ln "$SRC" "${DST_DIR}${DST}"
      elif [ -d $SRC ]; then
        _mkdir "$SRC"
      else
        _status "Can't handle $SRC"
      fi
    done
}

function _sudo() {
    if [[ $(groups "$USER") == *"sudo"* ]]; then
        sudo -E bash -c "source $BASE_DIR/install-lib; $*"
    else
        _status "Cannot become root: $*"
    fi
}
