"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Patrick McFarland"
email = "pmcfarland@adterrasperaspera.com"

[ui]
diff-formatter = ":git"

[colors]
"diff token" = { underline = false }

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'

[aliases]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]
