theme = "rootloops"

[editor]
line-number = "relative"
auto-completion = false
undercurl = true
color-modes = true
popup-border = "all"
auto-pairs = false

[editor.statusline]

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.smart-tab]
enable = true

[keys.normal]
"ins" = "insert_mode"
";" = "command_mode"
"S-k" = "hover"
"C-k" = "signature_help"

"y" = "yank_main_selection_to_clipboard"
"Y" = "yank_to_clipboard"
"p" = "paste_clipboard_before"
"P" = "paste_clipboard_after"

"x" = "extend_to_line_bounds"
"X" = "extend_line_below"

[keys.normal.space]
"q" = "wclose"
"w" = ":bclose"
"v" = "vsplit"

"y" = "no_op"
"Y" = "no_op"
"p" = "no_op"
"P" = "no_op"

[keys.normal.g]
"D" = "goto_declaration"

[keys.insert]
"ins" = "select_mode"

[keys.select]
"ins" = "normal_mode"
