[language-server.bash-language-server.config]
bashIde.shellcheckArguments = "-x -o all"

[language-server.efm-langserver]
command = "efm-langserver"

[language-server.rumdl]
command = "rumdl"
args = ["server", "-v"]

[language-servers.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "markdown"
auto-format = true
language-servers = ["rumdl"]

[[language]]
name = "rust"

[[language]]
name = "yaml"
auto-format = true
language-servers = ["efm-langserver"]
