[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language-server.bash-language-server.config]
bashIde.shellcheckArguments = "-x -o all"

[[language]]
name = "markdown"
auto-format = true
language-servers = [{ name = "efm", only-features = ["diagnostics", "format"] }]

[language-server.efm]
command = "efm-langserver"

[language-servers.rust-analyzer.config.check]
command = "clippy"
