[[language]]
name = "bash"
language-servers = [ "bash-language-server" ]
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language-servers.bash-language-server]
environment = { "SHELLCHECK_ARGUMENTS" = "-x -o all" }

[[language]]
name = "c"
language-servers = [ "clangd" ]

[[language]]
name = "cpp"
language-servers = [ "clangd" ]
# todo: See https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-serverss#cmake

[[language]]
name = "opencl"
language-servers = [ "clangd" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server" ]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server" ]

[[language]]
name = "json"
language-servers = [ "vscode-json-language-server" ]

# [[language]]
# name = "jsonc"
# language-servers = [ "vscode-json-language-server" ]

[[language]]
name = "lua"
language-servers = [ "lua-language-server" ]

[[language]]
name = "markdown"
language-servers = [
  { name = "efm", only-features = [ "diagnostics", "format" ] }
]

[language-server.efm]
command = "efm-langserver"

[[language]]
name = "toml"
language-servers = [ "taplo" ]

[[language]]
name = "rust"
language-servers = [ "rust-analyzer" ]

[language-servers.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "xml"
language-servers = [ "lemminx" ]

[language-server.lemminx]
command = "lemminx"
