#!/bin/bash

# shellcheck disable=SC1090  # can't follow non-constant source
# shellcheck disable=SC1091  # can't follow source
# shellcheck disable=SC2034  # unused variables

# if not interactive, exit early
[ -z "$PS1" ] && return
shopt -oq posix && return

# path: home, $PATH, sbin
# global is assumed to contain at least: /usr/local/bin:/usr/bin:/bin
PATH=$HOME/bin:$HOME/.cargo/bin:$HOME/.emacs.d/bin:$PATH:/usr/local/sbin:/usr/sbin:/sbin

shopt -s globstar
for p in "$HOME"/bin/**/*; do
    if [ -d "$p" ]; then
	PATH="$p:$PATH";
    fi
done
shopt -u globstar

# noramlize locale
LC_CTYPE=en_US.UTF-8

# override tmux $TERM
if [ "$TERM" == "tmux-256color" ]; then
    TERM=tmux-direct
fi

# set editor
EDITOR=emacs
VISUAL=emacs
GIT_EDITOR=emacs

# set window size
shopt -s checkwinsize

# recursive glob
shopt -s globstar 2> /dev/null

# case-insensitive glob
shopt -s nocaseglob

# append, not overwrite, history
shopt -s histappend

# save multi-line commands as single entry with embeded newlines
shopt -s cmdhist
shopt -s lithist

# force expand variable in tab complete to prevent escaping $
shopt -s direxpand

# unlimited power
HISTSIZE=999999999
HISTFILESIZE=999999999

# ignore deps
HISTCONTROL="erasedups:ignoreboth"

# don't record useless commands
HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"

# ignore case for autocomplete
bind "set completion-ignore-case on"

# ... including - and _
bind "set completion-map-case on"

# don't require tab twice to get list
bind "set show-all-if-ambiguous on"

# treat symlinked dirs as dirs
bind "set mark-symlinked-directories on"

# colors and paren matching
bind "set blink-matching-paren on"
bind "set colored-completion-prefix on"
bind "set colored-stats on"

# add bash-completion when available
if [ -f /usr/share/bash-completion/bash_completion ]; then
    source /usr/share/bash-completion/bash_completion
elif [ -f /etc/bash_completion ]; then
    source /etc/bash_completion
fi

# add git-prompt when available
GIT_PS1_SHOWCOLORHINTS=true
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWSTASHSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWUPSTREAM=auto

if [[ -a /usr/share/git/completion/git-prompt.sh ]]; then
    source /usr/share/git/completion/git-prompt.sh
elif [[ -a /usr/lib/git-core/git-sh-prompt ]]; then
    source /usr/lib/git-core/git-sh-prompt
fi

# colors
RESET=$(tput sgr0)
BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)

# hostname color
HOSTCHECKSUM=$(echo "$HOSTNAME" | md5sum | tr '[:lower:]' '[:upper:]' | cut -b1-2)
HOSTCOLOR=$(( 16#"$HOSTCHECKSUM"%8 ))

case $HOSTCOLOR in
    0)
	PRO_FG=$(tput setaf "$HOSTCOLOR")$(tput setab "$WHITE")
	;;
    *)
	PRO_FG=$(tput setaf "$HOSTCOLOR")
	;;
esac

unset HOSTCHECKSUM
unset HOSTCOLOR

# set prompt
PRO_START="[\\[$PRO_FG\\]\\h\\[$RESET\\] \\W"

if [ "$(id -u)" -eq 0 ]; then
    PRO_END="]\\[$RED\\]#\\[$RESET\\] "
else
    PRO_END="]\$ "
fi

precmd() {
    if [[ x$PWD != x$HOME ]] && [ x"$(type -t __git_ps1)" = x'function' ]; then
	__git_ps1 "$PRO_START" "$PRO_END"
    else
	PS1=$PRO_START$PRO_END
    fi

    if [[ -n $TMUX ]]; then
	eval "$(tmux show-environment -s)"
    fi

    history -a
}

PROMPT_COMMAND=precmd

# set xterm title
preexec() {
    if [[ $BASH_COMMAND == "precmd" ]]; then
	COMMAND=${DIRSTACK[*]}
    else
	COMMAND=$BASH_COMMAND
    fi

    PRO_TITLE="\\033]0;${HOSTNAME%%.*}: $COMMAND\\007"
    echo -ne "$PRO_TITLE"
}

trap preexec DEBUG

# load local config
if [[ -a ~/.bashrc.local ]]; then
    source ~/.bashrc.local
fi

# aliases
alias bc="bc -ql"
alias emacs="TERM=xterm-emacs emacs"
alias grep="grep --color=auto"
alias ls="ls --color=auto"

if [ -f /usr/share/doc/fzf/examples/completion.bash ]; then
     source /usr/share/doc/fzf/examples/completion.bash
fi

if command -v zoxide &> /dev/null; then
    eval "$(zoxide init bash --cmd cd)" &> /dev/null
fi
