PATH=$HOME/bin:/usr/local/opt/coreutils/libexec/gnubin::/usr/local/bin:$PATH

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.zsh/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-extras tmux autojump brew)

source $ZSH/oh-my-zsh.sh

setopt no_hup
unsetopt check_jobs
setopt inc_append_history
unsetopt share_history
unsetopt correct_all

RESET=%f%k
RED=%F{001}
GREEN=%F{002}
YELLOW=%F{003}
BLUE=%F{004}
PURPLE=%F{005}
CYAN=%F{006}
ORANGE=%F{009}
BROWN=%F{014}

if [ $(id -u) -eq 0 ]; then
	PRO_SYM="$RED#$RESET"
else
	PRO_SYM="\$"
fi

case $HOST in
[a-d]*)
	PRO_FG=$GREEN
	;;
[f-h]*)
	PRO_FG=$YELLOW
	;;
[i-l]*)
	PRO_FG=$BLUE
	;;
[m-p]*)
	PRO_FG=$ORANGE
	;;
[q-t]*)
	PRO_FG=$CYAN
	;;
[u-w]*)
	PRO_FG=$PURPLE
	;;
[x-z]*)
	PRO_FG=$BROWN
	;;
esac

ZSH_THEME_GIT_PROMPT_PREFIX=" "
ZSH_THEME_GIT_PROMPT_SUFFIX=
ZSH_THEME_GIT_PROMPT_DIRTY=" $RED\u2717$RESET"
ZSH_THEME_GIT_PROMPT_CLEAN=" $GREEN\u2713$RESET"

ZSH_THEME_GIT_PROMPT_ADDED="$YELLOW\u002B$RESET"
ZSH_THEME_GIT_PROMPT_MODIFIED="$YELLOW\u00B1$RESET"
ZSH_THEME_GIT_PROMPT_DELETED="$YELLOW\u002D$RESET"
ZSH_THEME_GIT_PROMPT_UNTRACKED="$YELLOW\u003F$RESET"
ZSH_THEME_GIT_PROMPT_RENAMED="$YELLOW\u2192$RESET"
ZSH_THEME_GIT_PROMPT_UNMERGED="$YELLOW\u0021$RESET"
ZSH_THEME_GIT_PROMPT_AHEAD="$BLUE\u2193$RESET"
ZSH_THEME_GIT_PROMPT_BEHIND="$BLUE\u2191$RESET"
ZSH_THEME_GIT_PROMPT_DIVERGED="$BLUE\u21F5$RESET"

PRO_GIT=$'$(git_prompt_info)$(git_prompt_status)'

PROMPT="[$PRO_FG%m$RESET %3~$PRO_GIT]$PRO_SYM "

ERR_FG=$RED

RPROMPT=$'%(?..$ERR_FG\u21B3$RESET $?)'

