[options]
  colorscheme = "one"
  colorscheme_bg = "dark"
  enable_guicolors = true

  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 3
  statusline_unicode_symbols = false
  enable_tabline_filetype_icon = false
  enable_statusline_mode = false
  relativenumber = false

  filemanager = "nerdtree"

  autocomplete_parens = false
  expand_tab = true

  bootstrap_before = 'override#before'

[[layers]]
  name = 'core'
  filetree_show_hidden = true

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "smart"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'colorscheme'

[[layers]]
  name = 'gtags'

[[layers]]
  name = 'leaderf'

[[layers]]
  name = 'sudo'

[[layers]]
  name = 'tmux'

[[layers]]
  name = 'lang#json'

[[layers]]
  name = 'lang#perl'

[[layers]]
  name = 'lang#sh'

[[layers]]
  name = 'lang#toml'

[[layers]]
  name = 'lang#xml'

[[layers]]
  name = 'lang#vim'
