shell = { program = "bash", args = ["-l"] }

[env]
TERM = "alacritty"
WSLENV = "TERM/u"

[font]
normal = { family = "Iosevka Term", style = "Regular" }
bold = { family = "Iosevka Term", style = "Medium" }
italic = { family = "Iosevka Term", style = "Italic" }
bold_italic = { family = "Iosevka Term", style = "Medium Italic" }
size = 14
offset = { x = 1, y = 1 }
glyph_offset = { x = 0, y = 1 }

[window]
dimensions = { columns = 80, lines = 25 }
resize_increments = true

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
