import:
  - ~/.config/alacritty/keys.yml
  - ~\AppData\Roaming\alacritty\keys.yml

font:
  normal:
    family: Input Mono
    style: Regular
  bold:
    family: Input Mono
    style: Bold
  italic:
    family: Input Mono
    style: Italic
  bold_italic:
    family: Input Mono
    style: Bold Italic
  size: 12 # 16px, gives 192x54 on 1080p
  offset:
    x: 0
    y: 1
  glyph_offset:
    x: 0
    y: 1

shell:
  program: wsl.exe
  args:
    - ~ -d Debian

window:
  dimensions:
    columns: 132
    lines: 25

  dynamic_title: true

selection:
  save_to_clipboard: true

mouse:
  hide_when_typing: true

key_bindings:
  - { key: F11, action: ToggleFullscreen }
  - { key: D, mods: Control|Alt|Shift|Super, chars: "\x01d" }
  - { key: E, mods: Control|Alt|Shift|Super, chars: "\x01e" }
  - { key: R, mods: Control|Alt|Shift|Super, chars: "\x01r" }
  - { key: Z, mods: Control|Alt|Shift|Super, chars: "\x01z" }
  - { key: V, mods: Control|Alt|Shift|Super, chars: "\x01v" }
  - { key: H, mods: Control|Alt|Shift|Super, chars: "\x01h" }
  - { key: Semicolon, mods: Control|Alt|Shift|Super, chars: "\x01;" }
  - { key: Colon, mods: Control|Alt|Shift|Super, chars: "\x01:" }
  - { key: Grave, mods: Control|Alt|Shift|Super, chars: "\x01`" }
  - { key: Key1, mods: Control|Alt|Shift|Super, chars: "\x011" }
  - { key: Key2, mods: Control|Alt|Shift|Super, chars: "\x012" }
  - { key: Key3, mods: Control|Alt|Shift|Super, chars: "\x013" }
  - { key: Key4, mods: Control|Alt|Shift|Super, chars: "\x014" }
  - { key: Key5, mods: Control|Alt|Shift|Super, chars: "\x015" }
  - { key: Key6, mods: Control|Alt|Shift|Super, chars: "\x016" }
  - { key: Key7, mods: Control|Alt|Shift|Super, chars: "\x017" }
  - { key: Key8, mods: Control|Alt|Shift|Super, chars: "\x018" }
  - { key: Key9, mods: Control|Alt|Shift|Super, chars: "\x019" }
  - { key: Key0, mods: Control|Alt|Shift|Super, chars: "\x010" }
