import:
    - ~/.config/alacritty/keys.yml
    - ~\AppData\Roaming\alacritty\keys.yml

font:
    normal:
        family: Iosevka Term
        style: Medium
    bold:
        family: Iosevka Term
        style: Extrabold
    italic:
        family: Iosevka Term
        style: Italic
    bold_italic:
        family: Iosevka Term
        style: Extrabold Italic
    size: 18
    offset:
      x: 0
      y: 0

shell:
    program: wsl.exe
    args:
        - ~ -d Debian

window:
    dimensions:
        columns: 80
        lines: 25

    dynamic_title: true

selection:
    save_to_clipboard: true

mouse:
    hide_when_typing: true

key_bindings:
    - { key: F11, action: ToggleFullscreen }
    - { key: LWin,  mods: Control|Alt|Shift|Super, chars: "\x01" }
