import:
  - ~/.config/alacritty/keys.yml
  - ~\AppData\Roaming\alacritty\keys.yml

env:
  TERM: alacritty
  WSLENV: TERM/u

font:
  normal:
    family: Iosevka Term
    style: Extended
  bold:
    family: Iosevka Term
    style: Bold Extended
  italic:
    family: Iosevka Term
    style: Extended Italic
  bold_italic:
    family: Iosevka Term
    style: Bold Extended Italic
  size: 18
  # 18pt/24px = 137x36 on 1920x1080, 24pt/32px = 137x40 on 2560x1600
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 1
    y: 0

shell:
  program: bash
  args:
    - -l

window:
  dimensions:
    columns: 80
    lines: 25

  dynamic_title: true

selection:
  save_to_clipboard: true

mouse:
  hide_when_typing: true

colors:
  primary:
    background: "#000000"
    foreground: "#C7C7C7"
  dim:
    black: "#000000"
    red: "#B10B00"
    green: "#376E00"
    yellow: "#745B00"
    blue: "#3122FF"
    magenta: "#8D00B6"
    cyan: "#006E60"
    white: "#919191"
  normal:
    black: "#2e2e2e"
    red: "#FF3D2B"
    green: "#57A900"
    yellow: "#B18C00"
    blue: "#6786FF"
    magenta: "#CC41FF"
    cyan: "#00A894"
    white: "#C7C7C7"
  bright:
    black: "#5E5E5E"
    red: "#FFAFA2"
    green: "#7AE700"
    yellow: "#F1C000"
    blue: "#B1C5FF"
    magenta: "#E6ADFF"
    cyan: "#00E6CA"
    white: "#FFFFFF"

key_bindings:
  - { key: F11, action: ToggleFullscreen }
  - { key: D, mods: Control|Alt|Shift|Super, chars: "\x01d" }
  - { key: E, mods: Control|Alt|Shift|Super, chars: "\x01e" }
  - { key: R, mods: Control|Alt|Shift|Super, chars: "\x01r" }
  - { key: Z, mods: Control|Alt|Shift|Super, chars: "\x01z" }
  - { key: V, mods: Control|Alt|Shift|Super, chars: "\x01v" }
  - { key: H, mods: Control|Alt|Shift|Super, chars: "\x01h" }
  - { key: Semicolon, mods: Control|Alt|Shift|Super, chars: "\x01;" }
  - { key: Colon, mods: Control|Alt|Shift|Super, chars: "\x01:" }
  - { key: Grave, mods: Control|Alt|Shift|Super, chars: "\x01`" }
  - { key: Key1, mods: Control|Alt|Shift|Super, chars: "\x011" }
  - { key: Key2, mods: Control|Alt|Shift|Super, chars: "\x012" }
  - { key: Key3, mods: Control|Alt|Shift|Super, chars: "\x013" }
  - { key: Key4, mods: Control|Alt|Shift|Super, chars: "\x014" }
  - { key: Key5, mods: Control|Alt|Shift|Super, chars: "\x015" }
  - { key: Key6, mods: Control|Alt|Shift|Super, chars: "\x016" }
  - { key: Key7, mods: Control|Alt|Shift|Super, chars: "\x017" }
  - { key: Key8, mods: Control|Alt|Shift|Super, chars: "\x018" }
  - { key: Key9, mods: Control|Alt|Shift|Super, chars: "\x019" }
  - { key: Key0, mods: Control|Alt|Shift|Super, chars: "\x010" }
