import:
  - ~/.config/alacritty/keys.yml
  - ~\AppData\Roaming\alacritty\keys.yml

env:
  TERM: alacritty
  WSLENV: TERM/u

font:
  normal:
    family: Iosevka Term
    style: Medium
  bold:
    family: Iosevka Term
    style: Heavy
  italic:
    family: Iosevka Term
    style: Medium Italic
  bold_italic:
    family: Iosevka Term
    style: Heavy Italic
  size: 16.5

  # Iosevka
  #              | 1920x1080 | 2560x1600 |
  # -------------|-----------|-----------|
  # 12.75pt/17px | 240x54    |           |
  # 16.5pt/22px  | 192x40    |           |
  # 18pt/24px    | 160x36    |           |
  # 24pt/32px    | 120x27    | 160x40    |
  # 36pt/48px    | 80x18     |           |

  # Laptop args: -o font.size=12 -o font.offset.y=-1 -o font.glyph_offset=-1

  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

shell:
  program: bash
  args:
    - -l

window:
  dimensions:
    columns: 80
    lines: 25

  dynamic_title: true
  resize_increments: true

selection:
  save_to_clipboard: true

mouse:
  hide_when_typing: true

colors:
  primary:
    background: "#000000"
    foreground: "#C7C7C7"
  dim:
    black: "#000000"
    red: "#B10B00"
    green: "#376E00"
    yellow: "#745B00"
    blue: "#3122FF"
    magenta: "#8D00B6"
    cyan: "#006E60"
    white: "#919191"
  normal:
    black: "#2e2e2e"
    red: "#FF3D2B"
    green: "#57A900"
    yellow: "#B18C00"
    blue: "#6786FF"
    magenta: "#CC41FF"
    cyan: "#00A894"
    white: "#C7C7C7"
  bright:
    black: "#5E5E5E"
    red: "#FFAFA2"
    green: "#7AE700"
    yellow: "#F1C000"
    blue: "#B1C5FF"
    magenta: "#E6ADFF"
    cyan: "#00E6CA"
    white: "#FFFFFF"

key_bindings:
  - { key: F11, action: ToggleFullscreen }
